runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyA-jRxPfCbdfcNPPn0BQXCtNGZPjWLotDY

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10